/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminModifyPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminModify_Page
     */
    public AdminModifyPage() {
        initComponents();
        LCKTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ModifyTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhoneNoF = new javax.swing.JTextField();
        AddFunc = new javax.swing.JButton();
        DeleteFunc = new javax.swing.JButton();
        EditFunc = new javax.swing.JButton();
        ReturnB = new javax.swing.JButton();

        ModifyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ModifyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ModifyTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("User Modify ");

        jLabel1.setText("ID:  ");

        jLabel2.setText("Name:");

        jLabel3.setText("Phone No:");

        AddFunc.setText("Add");
        AddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFuncActionPerformed(evt);
            }
        });

        DeleteFunc.setText("Delete");
        DeleteFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFuncActionPerformed(evt);
            }
        });

        EditFunc.setText("Edit");
        EditFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IDF, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(NameF)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneNoF))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(AddFunc)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteFunc)
                        .addGap(18, 18, 18)
                        .addComponent(EditFunc)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneNoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFunc)
                    .addComponent(DeleteFunc)
                    .addComponent(EditFunc))
                .addGap(52, 52, 52))
        );

        ReturnB.setBackground(new java.awt.Color(255, 102, 102));
        ReturnB.setText("Return");
        ReturnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(222, 222, 222)
                .addComponent(ReturnB)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 469, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ReturnB, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFuncActionPerformed
        File file = new File("AdminDetail.txt");

        if(IDF.getText().equals("")||NameF.getText().equals("")||PhoneNoF.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter All Data!");

        }else{

            try {
                FileWriter FW = new FileWriter (file,true);
                BufferedWriter BW = new BufferedWriter(FW);
                String record = IDF.getText() + ":" + NameF.getText() + ":" + PhoneNoF.getText();
                BW.write(record);
                String data[] = {IDF.getText(),NameF.getText(),PhoneNoF.getText()};

                DefaultTableModel Table = (DefaultTableModel)ModifyTable.getModel();

                Table.addRow(data);

                JOptionPane.showMessageDialog(this,"Add Data Successfully...!");
                IDF.setText("");
                NameF.setText("");
                PhoneNoF.setText("");
                BW.close();
                FW.close();

            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_AddFuncActionPerformed

    private void DeleteFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFuncActionPerformed
        DefaultTableModel Table = (DefaultTableModel)ModifyTable.getModel();
        File file = new File("AdminDetail.txt");

        if(ModifyTable.getSelectedRowCount()==1) {
            Table.removeRow(ModifyTable.getSelectedRow());
            JOptionPane.showMessageDialog(this,"Delete Data Successfully...!");
            try {
                FileWriter FW = new FileWriter (file,false);
                BufferedWriter BW = new BufferedWriter(FW);
                BW.write("ID:Name:Phone No\n");
                for(int i = 0; i < ModifyTable.getRowCount();i++){
                    for(int j = 0;j < ModifyTable.getColumnCount(); j++){
                        BW.write(ModifyTable.getModel().getValueAt(i,j)+":");
                    }
                    BW.write("\n");
                }
                BW.close();
                FW.close();
            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(ModifyTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty!");
            }else{
                JOptionPane.showMessageDialog(this,"Please Select A Row to Delete the Data!");
            }
        }
    }//GEN-LAST:event_DeleteFuncActionPerformed

    private void EditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFuncActionPerformed
        DefaultTableModel Table = (DefaultTableModel)ModifyTable.getModel();
        File file = new File("AdminDetail.txt");

        if(ModifyTable.getSelectedRowCount()==1) {

            String id = IDF.getText();
            String name = NameF.getText();
            String phoneNo = PhoneNoF.getText();

            Table.setValueAt(id, ModifyTable.getSelectedRow(),0);
            Table.setValueAt(name, ModifyTable.getSelectedRow(),1);
            Table.setValueAt(phoneNo, ModifyTable.getSelectedRow(),2);

            JOptionPane.showMessageDialog(this,"Update Successfully... !");

            try {
                FileWriter FW = new FileWriter (file,false);
                BufferedWriter BW = new BufferedWriter(FW);
                BW.write("ID:Name:Phone No\n");
                for(int i = 0; i < ModifyTable.getRowCount();i++){
                    for(int j = 0;j < ModifyTable.getColumnCount(); j++){
                        BW.write(ModifyTable.getModel().getValueAt(i,j)+":");
                    }
                    BW.write("\n");
                }
                BW.close();
                FW.close();
            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(ModifyTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty !");
            }else{
                JOptionPane.showMessageDialog(this,"Please Select A Row to Update the Data!");
            }
        }
    
    }//GEN-LAST:event_EditFuncActionPerformed

    private void ModifyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyTableMouseClicked
        DefaultTableModel Table = (DefaultTableModel)ModifyTable.getModel();
        
        String id = Table.getValueAt(ModifyTable.getSelectedRow(), 0).toString();
        String name = Table.getValueAt(ModifyTable.getSelectedRow(), 1).toString();
        String phoneNo = Table.getValueAt(ModifyTable.getSelectedRow(), 2).toString();

        IDF.setText(id);
        NameF.setText(name);
        PhoneNoF.setText(phoneNo);
    }//GEN-LAST:event_ModifyTableMouseClicked

    private void ReturnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBActionPerformed
        UserManagementPage r = new UserManagementPage();
        r.show();

        dispose();
    }//GEN-LAST:event_ReturnBActionPerformed

      public void LCKTable() {

          File itemfile = new File("AdminDetail.txt");

        try {
            if (itemfile.createNewFile()) {
                FileOutputStream opFile = new FileOutputStream(itemfile, false);
            } else {
                FileReader fr = new FileReader(itemfile);
                BufferedReader br = new BufferedReader(fr);
                String rec = br.readLine().trim();
                String[] colHeader = rec.split(":");

                DefaultTableModel Model = (DefaultTableModel) ModifyTable.getModel();
                Model.setColumnIdentifiers(colHeader);

                Object[] tableLines = br.lines().toArray();
                int i;
                
                for (i = 0; i < tableLines.length;i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                Model.addRow(dataRow);
            }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPage.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFunc;
    private javax.swing.JButton DeleteFunc;
    private javax.swing.JButton EditFunc;
    private javax.swing.JTextField IDF;
    private javax.swing.JTable ModifyTable;
    private javax.swing.JTextField NameF;
    private javax.swing.JTextField PhoneNoF;
    private javax.swing.JButton ReturnB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
