/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DeliveryModifyPage extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryModifyPage
     */
    public DeliveryModifyPage() {
        initComponents();
        LCKTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDF = new javax.swing.JTextField();
        NameF = new javax.swing.JTextField();
        PriceF = new javax.swing.JTextField();
        StatusF = new javax.swing.JTextField();
        AddF = new javax.swing.JButton();
        DeleteF = new javax.swing.JButton();
        EditF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveryTable = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("Delivery Staff Modify ");

        jLabel1.setText("Food ID: ");

        jLabel2.setText("Food Name:");

        jLabel3.setText("Food Price:");

        jLabel4.setText("Delivery Status:");

        AddF.setText("Add");
        AddF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFActionPerformed(evt);
            }
        });

        DeleteF.setText("Delete");
        DeleteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFActionPerformed(evt);
            }
        });

        EditF.setText("Edit");
        EditF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameF, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(PriceF)
                            .addComponent(IDF)
                            .addComponent(StatusF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(AddF)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteF)
                        .addGap(18, 18, 18)
                        .addComponent(EditF)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PriceF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(StatusF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddF)
                    .addComponent(DeleteF)
                    .addComponent(EditF))
                .addGap(55, 55, 55))
        );

        DeliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DeliveryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeliveryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DeliveryTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFActionPerformed
        File file = new File("DeliveryDetail.txt");

        if(IDF.getText().equals("")||NameF.getText().equals("")||PriceF.getText().equals("")||StatusF.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter All Data!");

        }else{

            try {
                FileWriter FW = new FileWriter (file,true);
                BufferedWriter BW = new BufferedWriter(FW);
                String record = IDF.getText() + ":" + NameF.getText() + ":" + PriceF.getText() + StatusF.getText();
                BW.write(record);
                String data[] = {IDF.getText(),NameF.getText(),PriceF.getText(),StatusF.getText()};

                DefaultTableModel Table = (DefaultTableModel)DeliveryTable.getModel();

                Table.addRow(data);

                JOptionPane.showMessageDialog(this,"Add Data Successfully...!");
                IDF.setText("");
                NameF.setText("");
                PriceF.setText("");
                StatusF.setText("");
                BW.close();
                FW.close();

            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_AddFActionPerformed

    private void DeleteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFActionPerformed
        DefaultTableModel Table = (DefaultTableModel)DeliveryTable.getModel();
        File file = new File("DeliveryDetail.txt");

        if(DeliveryTable.getSelectedRowCount()==1) {
            Table.removeRow(DeliveryTable.getSelectedRow());
            JOptionPane.showMessageDialog(this,"Delete Data Successfully...!");
            try {
                FileWriter FW = new FileWriter (file,false);
                BufferedWriter BW = new BufferedWriter(FW);
                BW.write("Food ID:Food Name:Food Price:Delivery Status\n");
                for(int i = 0; i < DeliveryTable.getRowCount();i++){
                    for(int j = 0;j < DeliveryTable.getColumnCount(); j++){
                        BW.write(DeliveryTable.getModel().getValueAt(i,j)+":");
                    }
                    BW.write("\n");
                }
                BW.close();
                FW.close();
            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(DeliveryTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty!");
            }else{
                JOptionPane.showMessageDialog(this,"Please Select A Row to Delete the Data!");
            }
        }
    }//GEN-LAST:event_DeleteFActionPerformed

    private void EditFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFActionPerformed
        DefaultTableModel Table = (DefaultTableModel)DeliveryTable.getModel();
        File file = new File("DeliveryDetail.txt");

        if(DeliveryTable.getSelectedRowCount()==1) {

            String id = IDF.getText();
            String name = NameF.getText();
            String price = PriceF.getText();
            String status = StatusF.getText();

            Table.setValueAt(id, DeliveryTable.getSelectedRow(),0);
            Table.setValueAt(name, DeliveryTable.getSelectedRow(),1);
            Table.setValueAt(price, DeliveryTable.getSelectedRow(),2);
            Table.setValueAt(status, DeliveryTable.getSelectedRow(),3);

            JOptionPane.showMessageDialog(this,"Update Successfully... !");

            try {
                FileWriter FW = new FileWriter (file,false);
                BufferedWriter BW = new BufferedWriter(FW);
                BW.write("Food ID:Food Name:Food Price:Delivery Status\n");
                for(int i = 0; i < DeliveryTable.getRowCount();i++){
                    for(int j = 0;j < DeliveryTable.getColumnCount(); j++){
                        BW.write(DeliveryTable.getModel().getValueAt(i,j)+":");
                    }
                    BW.write("\n");
                }
                BW.close();
                FW.close();
            }catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(DeliveryTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty !");
            }else{
                JOptionPane.showMessageDialog(this,"Please Select A Row to Update the Data!");
            }
        }
    }//GEN-LAST:event_EditFActionPerformed

    private void DeliveryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeliveryTableMouseClicked
        DefaultTableModel Table = (DefaultTableModel)DeliveryTable.getModel();
        
        String id = Table.getValueAt(DeliveryTable.getSelectedRow(), 0).toString();
        String name = Table.getValueAt(DeliveryTable.getSelectedRow(), 1).toString();
        String price = Table.getValueAt(DeliveryTable.getSelectedRow(), 2).toString();
        String status = Table.getValueAt(DeliveryTable.getSelectedRow(), 3).toString();

        IDF.setText(id);
        NameF.setText(name);
        PriceF.setText(price);
        StatusF.setText(status);
    }//GEN-LAST:event_DeliveryTableMouseClicked

     public void LCKTable() {

          File itemfile = new File("DeliveryDetail.txt");

        try {
            if (itemfile.createNewFile()) {
                FileOutputStream opFile = new FileOutputStream(itemfile, false);
            } else {
                FileReader fr = new FileReader(itemfile);
                BufferedReader br = new BufferedReader(fr);
                String rec = br.readLine().trim();
                String[] colHeader = rec.split(":");

                DefaultTableModel Model = (DefaultTableModel) DeliveryTable.getModel();
                Model.setColumnIdentifiers(colHeader);

                Object[] tableLines = br.lines().toArray();
                int i;
                
                for (i = 0; i < tableLines.length;i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                Model.addRow(dataRow);
            }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPage.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryModifyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryModifyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddF;
    private javax.swing.JButton DeleteF;
    private javax.swing.JTable DeliveryTable;
    private javax.swing.JButton EditF;
    private javax.swing.JTextField IDF;
    private javax.swing.JTextField NameF;
    private javax.swing.JTextField PriceF;
    private javax.swing.JTextField StatusF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
